blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ GitHub Discussions
    url: https://github.com/1hostjs/hosting/discussions
    about: Discuss on our GitHub Discussions
  - name: â“ Get help
    url: https://github.com/1hostjs/hosting/discussions/new?category=Help
    about: Create a new help post
  - name: Look at our website!
    url: https://1host.js.org/
    about: Check our documentation and more.
